version: '3.8'

services:
  back-end:
    image: softy-pinko-back-end:task6
    deploy:
      replicas: 2  # This will create two instances of the back-end service
    # No port mapping to the host

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    # No port mapping to the host

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"  # Expose port 80 to the host
    depends_on:
      - front-end
      - back-end
